[toolchain]
profile = "minimal"
channel = "nightly"
components = ["rust-src", "rustfmt", "clippy"]
targets = ["riscv64imac-unknown-none-elf"] # "x86_64-unknown-none", "riscv64gc-unknown-none-elf", "aarch64-unknown-none-softfloat"
